### ISSUE TITLE
Depreciation of 12.1.1

### ISSUE THREAD

**Issue by damacus** [universityofderby/chef-weblogic#10]
12.1.1 is no longer available for download from Oracle Technical Network, so I am in favour of deprecating support for it from the cookbook.

**Comment by hanskreuger** [comment]
+1 afaik 12.1.2 supersedes it in terms of oracle support

**Comment by damacus** [comment]
We'll still have support for 12.1.3 and 12.1.3 & 10.3.6 (!) 

I'll put this in after we've switched to custom_resources.
