### ISSUE TITLE
possible to get 10.3.5 support?

### ISSUE THREAD

**Issue by joshoohaah** [universityofderby/chef-weblogic#14]
I see that 10.3.6 is in there.   What is interesting is there are a handful of Oracle applications (v12) that only support 10.3.5 of weblogic installs/deployments.

**Comment by damacus** [comment]
@richardlock @rbarkley want to take a look at this one?

**Comment by damacus** [comment]
@joshoohaah The only reason it isn't supported right now is I don't have access to 10.3.5 edelivery & the support site both don't have a copy.
We've got two options:
- If you have a copy handy feel free to write a PR 👍 
- Drop me the installer and I'll add support

**Comment by joshoohaah** [comment]
try this @damacus . https://s3.amazonaws.com/gehc.preprod.useast1.swrepo/App-dump/wls1035_generic.jar

**Comment by damacus** [comment]
Thanks @joshoohaah

**Comment by damacus** [comment]
Added in the latest version.
