### ISSUE TITLE
Template refers to old cookbook name

### ISSUE THREAD

**Issue by richardlock** [universityofderby/chef-weblogic#3]
https://github.com/universityofderby/chef-weblogic/blob/0467a3fc53bd1f7259a489e3a012b56ea66bd74a/libraries/weblogic_server.rb#L120

Template refers to old cookbook name.

**Comment by damacus** [comment]
This one should be pretty easy to fix. You want this one @richardlock ?

**Comment by richardlock** [comment]
Thanks.  Yes, just working through it - there are some other issues with the cookbook following testing.  Hope you're enjoying freedom.

**Comment by damacus** [comment]
Cool. I might see if I can talk to Oracle and see if I can find a way to
download weblogic for public cookbook testing.
