### ISSUE TITLE
Rewrite using Chef 12.5 resource model

### ISSUE THREAD

**Issue by damacus** [universityofderby/chef-weblogic#8]
Chef 12.5 brings custom resources. 

https://docs.chef.io/custom_resources.html

We might not need to use the resource cookbook (which is causing a number of deprecation warnings and upload errors)

**Comment by hydrant25** [comment]
@damacus : I'm currently using this cookbook for some weblogic installs and ran into the same compatibility warnings as well as a failing berkshelf upload. Do you have a fork you're currently working on? Would you like help on it?

**Comment by damacus** [comment]
Yes! There's a branch for this at https://github.com/universityofderby/chef-weblogic/tree/custom_resources

I'm going to have a crack at it with @hanskreuger this week hopefully! 


Ideally I'd like to remove the oracle-inventory dep as well (but I haven't quite figured out how I'm going to do that yet )
